# Generated by Django 5.2.4 on 2025-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_progress_tracker_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
